"""add moodboard fields to collection_items

Revision ID: 667a7254f45d
Revises: 6c6a04e59ceb
Create Date: 2026-05-29 01:24:36.715671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667a7254f45d'
down_revision: Union[str, Sequence[str], None] = '6c6a04e59ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('x', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('collection_items', sa.Column('y', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('collection_items', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('collection_items', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('collection_items', sa.Column('z_index', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_items', 'z_index')
    op.drop_column('collection_items', 'height')
    op.drop_column('collection_items', 'width')
    op.drop_column('collection_items', 'y')
    op.drop_column('collection_items', 'x')
    # ### end Alembic commands ###
