"""Add sync_status to Artist

Revision ID: 6c6a04e59ceb
Revises: da5760fc7dd7
Create Date: 2026-05-28 17:44:56.100893

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6c6a04e59ceb'
down_revision: str | Sequence[str] | None = 'da5760fc7dd7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('sync_status', sa.String(length=50), server_default='ready', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'sync_status')
    # ### end Alembic commands ###
