"""add_is_pinned_to_artwork

Revision ID: b2a87db06dfd
Revises: 667a7254f45d
Create Date: 2026-05-29 02:52:59.432854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a87db06dfd'
down_revision: Union[str, Sequence[str], None] = '667a7254f45d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artworks', sa.Column('is_pinned', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artworks', 'is_pinned')
    # ### end Alembic commands ###
