"""add_artists_artworks

Revision ID: b99cf3fbf29b
Revises: 1d94230c320b
Create Date: 2026-05-28 13:41:08.968471

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b99cf3fbf29b'
down_revision: str | Sequence[str] | None = '1d94230c320b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('bio_short', sa.Text(), nullable=True),
    sa.Column('cover_artwork_id', sa.UUID(), nullable=True),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('artworks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artist_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('source_page_url', sa.String(length=2048), nullable=True),
    sa.Column('source_image_url', sa.String(length=2048), nullable=False),
    sa.Column('image_original', sa.String(length=2048), nullable=True),
    sa.Column('image_large', sa.String(length=2048), nullable=True),
    sa.Column('image_thumb', sa.String(length=2048), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('dominant_colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phash', sa.String(length=32), nullable=True),
    sa.Column('is_downloaded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'phash', name='uq_artwork_artist_phash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artworks')
    op.drop_table('artists')
    # ### end Alembic commands ###
