"""add rotation to collection_items

Revision ID: dbd8259be32e
Revises: b2a87db06dfd
Create Date: 2026-06-02 20:00:48.749495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd8259be32e'
down_revision: Union[str, Sequence[str], None] = 'b2a87db06dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_items', sa.Column('rotation', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_items', 'rotation')
    # ### end Alembic commands ###
